add file to publish to pypi
NSLS-II/conftrak pull request #2
Opened 2021-11-24 23:02 UTC by JunAishima

2021-11-25 00:11 UTC, mrakitin commented
We need to publish the first release on PyPI manually, and then can generate a token and add a workflow.

2021-11-29 16:41 UTC, mrakitin requested changes
Probably I pointed you to the configuration, that we subsequently updated with Josh in https://github.com/NSLS-II/nslsii/blob/master/.github/workflows/publish-pypi.yml. Could you get that config instead? It uses a more accurate variable name `TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}`.

2021-11-29 19:32 UTC, JunAishima commented
> Probably I pointed you to the configuration, that we subsequently updated with Josh in https://github.com/NSLS-II/nslsii/blob/master/.github/workflows/publish-pypi.yml. Could you get that config instead? It uses a more accurate variable name `TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}`.

I have brought in the changes you suggest with https://github.com/NSLS-II/conftrak/pull/2/commits/08b85800b67d457f22cb92b6152327b9c354e941 . of course, I will now have to apply the same change to the other repos!

2021-11-30 15:24 UTC, mrakitin approved these changes

2021-11-30 15:24 UTC, merged